/* Generated by AN DISI Unibo */ 
package it.unibo.incinerator

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Incinerator ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		
		        val BTIME = 4000L;
		        var start = "off";
		        var stato = "spento";
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outyellow("incinerator ready...")
						delay(1000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t06",targetState="start",cond=whenDispatch("activation_command"))
				}	 
				state("start") { //this:State
					action { //it:State
						CommUtils.outgreen("the incinerator has started...")
						 start ="on";  
						 stato = "burning";  
						forward("statoIn", "statoIn(burning)" ,"observedactor" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t17",targetState="handleBurn",cond=whenDispatch("startBurn"))
				}	 
				state("handleBurn") { //this:State
					action { //it:State
						 stato = "burning";  
						forward("statoIn", "statoIn(burning)" ,"observedactor" ) 
						CommUtils.outred("the incinerator is burning...")
						delay(15000) 
						emit("burnEnd", "burnEnd(finish)" ) 
						 stato = "spento";  
						forward("statoIn", "statoIn(spento)" ,"observedactor" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t28",targetState="handleBurn",cond=whenDispatch("startBurn"))
				}	 
			}
		}
} 
