/* Generated by AN DISI Unibo */ 
package it.unibo.test_observer

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Test_observer ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 var RP = 0 
			   var Inc = ""
			   var Ash = 0
			   var Op = ""
			   var result = ""
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outred("START TEST")
						delay(1000) 
						observeResource("localhost","8080","ctxsprintdue","observedactor","data")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t148",targetState="handleStart",cond=whenRequest("start_test"))
				}	 
				state("handleStart") { //this:State
					action { //it:State
						delay(5000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t249",targetState="handle_data",cond=whenDispatch("data"))
				}	 
				state("handle_data") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("data(X,Y,Z,K)"), Term.createTerm("data(X,Y,Z,K)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 RP = payloadArg(0).toInt()
											   Inc = payloadArg(1)
											   Ash = payloadArg(2).toInt()	
											   Op = payloadArg(3)
											   var result = "$RP, $Inc, $Ash, $Op"
						}
						answer("start_test", "start_test_reply", "start_test_reply("$result")"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
