/* Generated by AN DISI Unibo */ 
package it.unibo.sonar_device

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Sonar_device ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 var K= 0  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outyellow("START sonar_device")
						 K= 1000  
						delay(1500) 
						emitLocalStreamEvent("sonardata", "sonardata($K)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="half_empty", cond=doswitch() )
				}	 
				state("half_empty") { //this:State
					action { //it:State
						delay(30000) 
						 K= 500  
						delay(1500) 
						emitLocalStreamEvent("sonardata", "sonardata($K)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="full", cond=doswitch() )
				}	 
				state("full") { //this:State
					action { //it:State
						delay(30000) 
						 K= 0  
						delay(1500) 
						emitLocalStreamEvent("sonardata", "sonardata($K)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="empty", cond=doswitch() )
				}	 
				state("empty") { //this:State
					action { //it:State
						delay(30000) 
						 K= 1000  
						delay(1500) 
						emitLocalStreamEvent("sonardata", "sonardata($K)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="half_empty", cond=doswitch() )
				}	 
			}
		}
} 
